networks:
  app-network:
    driver: bridge

services:
  eureka-server:
    build: ./backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  user-service:
    build: ./backend/user-service
    container_name: user-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/userdb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/authdb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: lamdieuquang0105@gmail.com
      SPRING_MAIL_PASSWORD: nfvlsoakxndkbusr
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JWT_EXPIRATION: 86400000
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  product-service:
    build: ./backend/product-service
    container_name: product-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/productdb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      CLOUDINARY_CLOUD_NAME: dpj5pgpio
      CLOUDINARY_API_KEY: 555918594727174
      CLOUDINARY_API_SECRET: c-6uF0zMMgFWgypBaHx5C0FxMmk
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  category-service:
    build: ./backend/category-service
    container_name: category-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/categorydb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      CLOUDINARY_CLOUD_NAME: dpj5pgpio
      CLOUDINARY_API_KEY: 555918594727174
      CLOUDINARY_API_SECRET: c-6uF0zMMgFWgypBaHx5C0FxMmk
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  brand-service:
    build: ./backend/brand-service
    container_name: brand-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/branddb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  order-service:
    build: ./backend/order-service
    container_name: order-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/orderdb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      DATASOURCE_URL: jdbc:mysql://mysql-44edd1f-lamdieuquang0105-f460.j.aivencloud.com:10104/paymentdb?ssl-mode=REQUIRED
      DATASOURCE_USERNAME: avnadmin
      DATASOURCE_PASSWORD: AVNS_YswmtLsflqLrvYnNU40
      FRONTEND_URL: http://localhost:5173
      BACKEND_URL: http://localhost:8084
      MOMO_PARTNERCODE: OMO
      MOMO_ACCESSKEY: F8BBA842ECF85
      MOMO_SECRETKEY: K951B6PE1waDMi640xX08PD3vg6EkVlz
      MOMO_URL: https://test-payment.momo.vn/v2/gateway/api/create
      MOMO_REFUND_URL: https://test-payment.momo.vn/v2/gateway/api/refund
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  cart-service:
    build: ./backend/cart-service
    container_name: cart-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      SPRING_DATA_MONGODB_URI: mongodb+srv://lamdieuquang0105_db_user:LaoWbM56gHxZvnsy@nckh.sshybvd.mongodb.net/cartdb?appName=nckh&retryWrites=true&w=majority
      SPRING_DATA_REDIS_HOST: fresh-ox-19894.upstash.io
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: AU22AAIncDI1OWM4MzI3YjE3M2Y0NDVkODE5NWQ3YWI2NDkxMzExZnAyMTk4OTQ
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  chat-service:
    build: ./backend/chat-service
    container_name: chat-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      SPRING_DATA_MONGODB_URI: mongodb+srv://lamdieuquang0105_db_user:LaoWbM56gHxZvnsy@nckh.sshybvd.mongodb.net/chatdb?appName=nckh&retryWrites=true&w=majority
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  assistant-service:
    build: ./backend/assistant-service
    container_name: assistant-service
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      JWT_SECRET: d1b72a9c2f1b2cfd6eb0b9320491ec2f
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    networks:
      - app-network
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      FRONTEND_URL: http://localhost:5173
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: on-failure
