spring.application.name=payment-service
server.port=8084

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

momo.partnercode=${MOMO_PARTNERCODE}
momo.accesskey=${MOMO_ACCESSKEY}
momo.secretkey=${MOMO_SECRETKEY}
momo.url=${MOMO_URL}
momo.ipn-url=${BACKEND_URL}/api/payment/momo/redirect
momo.redirect-url=${BACKEND_URL}/api/payment/momo/redirect
momo.refund-url=${MOMO_REFUND_URL}