spring.application.name=assistant-service
server.port=${PORT:8087}

# Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Zipkin
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Tracing sampler
management.tracing.sampling.probability=1.0

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.should-enforce-registration-at-init=false
eureka.client.eureka-server-connect-timeout-seconds=10
eureka.client.eureka-server-read-timeout-seconds=10
eureka.client.registry-fetch-interval-seconds=30

jwt.secret=${JWT_SECRET}

n8n.url=${N8N_URL}
n8n.webhook=/webhook/ai-agent

