spring.application.name=cart-service
server.port=${PORT:8085}

# Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Zipkin
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Tracing sampler
management.tracing.sampling.probability=1.0

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.should-enforce-registration-at-init=false
eureka.client.eureka-server-connect-timeout-seconds=10
eureka.client.eureka-server-read-timeout-seconds=10
eureka.client.registry-fetch-interval-seconds=30

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.username=default
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.data.redis.enabled=true

jwt.secret=${JWT_SECRET}