spring.application.name=api-gateway

FRONTEND_URL=http://localhost:5173

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
