spring.application.name=api-gateway

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8089/realms/test

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
