spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-service:8089/realms/my-realm

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# USER SERVICE 8080
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# PRODUCT SERVICE 8081
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# CATEGORY SERVICE 8082
spring.cloud.gateway.routes[2].id=category-service
spring.cloud.gateway.routes[2].uri=lb://category-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/category/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# ORDER SERVICE 8083
spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://order-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/order/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# PAYMENT SERVICE 8084
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/payment/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

# CART SERVICE 8085
spring.cloud.gateway.routes[5].id=cart-service
spring.cloud.gateway.routes[5].uri=lb://cart-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/cart/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

# CHAT SERVICE 8086
spring.cloud.gateway.routes[6].id=chat-service
spring.cloud.gateway.routes[6].uri=lb://chat-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/chat/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

# ASSISTANT SERVICE 8087
spring.cloud.gateway.routes[7].id=assistant-service
spring.cloud.gateway.routes[7].uri=lb://assistant-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/assistant/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1

# BRAND SERVICE 8088
spring.cloud.gateway.routes[8].id=brand-service
spring.cloud.gateway.routes[8].uri=lb://brand-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/brand/**
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1

# AUTH SERVICE 8089
spring.cloud.gateway.routes[9].id=auth-service
spring.cloud.gateway.routes[9].uri=lb://auth-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[9].filters[0]=StripPrefix=1