spring.application.name=chat-service

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.data.mongodb.database=chatdb
spring.data.mongodb.uri=mongodb://localhost:27017/chatdb

jwt.secret=test-secret